### ISSUE TITLE
err by exectue app.js

### ISSUE THREAD

**Issue by yaodehaung** [kacole2/express-node-mongo-skeleton#3]
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
###### 
# 
# !!! MONGOOSE WARNING !!!
# 
# This is an UNSTABLE release of Mongoose.
# Unstable releases are available for preview/testing only.
# DO NOT run this in production.
# 
######

**Comment by kacole2** [comment]
@yaodehaung have you checked this error out? http://stackoverflow.com/questions/21656420/failed-to-load-c-bson-extension
